In [1]:
import numpy as np
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [2]:
array2 = np.array([(1,2,3),(4,5,6)])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

### array method

In [9]:
array2.flatten()

array([1, 2, 3, 4, 5, 6])

In [10]:
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
#dding a value of -1 in the designated new shape indicateing for NumPy to automatically infer the value based on other given values.
array2.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
array2.tolist()

[[1, 2, 3], [4, 5, 6]]

In [14]:
array2.max()

6

In [15]:
array2.min()

1

In [16]:
array2.mean()

3.5

In [17]:
array2.std()

1.707825127659933

### array attributes

In [19]:
array2.shape

(2, 3)

In [20]:
array2.dtype

dtype('int64')

In [21]:
array2.size

6

In [22]:
array2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
array2[1]

array([4, 5, 6])

In [24]:
array2[0,1]

2

In [25]:
array2[:,1]

array([2, 5])

In [26]:
array2[:,1:]

array([[2, 3],
       [5, 6]])

In [28]:
array2[1,1]=100
array2

array([[  1,   2,   3],
       [  4, 100,   6]])